### ISSUE TITLE
[Feature]Add support for co-re

### ISSUE THREAD

**Issue by Serinalice** [chriskaliX/Hades#33]
**Is your feature request related to a problem? Please describe.**
Deploy eBPF modules in product env. 

**Describe the solution you'd like**
* Compile .o files for common files or using btfhub.(the two methods are the same, essentially)
* Some suitable distribution and version control, and some CI/CD infras.

**Additional context**
https://github.com/aquasecurity/btfhub
https://github.com/cilium/cilium

**Comment by chriskaliX** [comment]
Thanks for reporting. I gonna support CO-RE this month, just like Tracee basically.

**Comment by chriskaliX** [comment]
1. **CO-RE**: Build eBPF driver in CO-RE way is supported now. BTFhub is not introduced for now, since the priority of backport CO-RE is relatively low, I think. And it is added to the dev plan, I will look into that.
2.  **Distribution and version control, CI/CD**: A brief CI/CD check for both CO-RE and non-co-re is updated while the kernel versions of non-co-re is limited for now, I will optimize this recently(Testing in more kernel version and different arch).

Again, thanks for suggesting! Feel free to reopen this issue or raise a new one if any idea was missed.
